2019-34-05 19:34:49 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-35-05 19:35:12 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-35-05 19:35:12 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:35:12] "GET /random?protocol=http HTTP/1.1" 500 -
2019-35-05 19:35:16 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-35-05 19:35:16 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:35:16] "GET /random?protocol=https HTTP/1.1" 500 -
2019-35-05 19:35:29 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-35-05 19:35:29 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:35:29] "GET /random HTTP/1.1" 500 -
2019-35-05 19:35:36 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-35-05 19:35:36 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:35:36] "GET /random HTTP/1.1" 500 -
2019-35-05 19:35:42 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-35-05 19:35:42 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:35:42] "GET /random HTTP/1.1" 500 -
2019-35-05 19:35:52 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-35-05 19:35:52 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:35:52] "GET /random HTTP/1.1" 500 -
2019-36-05 19:36:06 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-36-05 19:36:06 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:36:06] "GET /random?protocol=http HTTP/1.1" 500 -
2019-37-05 19:37:07 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-37-05 19:37:11 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-37-05 19:37:11 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:37:11] "GET /random?protocol=http HTTP/1.1" 500 -
2019-54-05 19:54:57 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-55-05 19:55:02 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-55-05 19:55:02 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:55:02] "GET /random?protocol=http HTTP/1.1" 500 -
2019-55-05 19:55:04 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-55-05 19:55:04 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:55:04] "GET /random?protocol=http HTTP/1.1" 500 -
2019-55-05 19:55:27 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-55-05 19:55:27 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:55:27] "GET /random?protocol=http HTTP/1.1" 500 -
2019-55-05 19:55:29 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-55-05 19:55:29 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:55:29] "GET /random HTTP/1.1" 500 -
2019-55-05 19:55:33 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-55-05 19:55:33 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:55:33] "GET /random HTTP/1.1" 500 -
2019-55-05 19:55:34 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-55-05 19:55:34 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:55:34] "GET /random HTTP/1.1" 500 -
2019-55-05 19:55:58 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-56-05 19:56:18 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-56-05 19:56:18 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:56:18] "GET /random?protocol=http HTTP/1.1" 500 -
2019-56-05 19:56:52 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-56-05 19:56:52 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:56:52] "GET /random?protocol=https HTTP/1.1" 500 -
2019-56-05 19:56:54 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-56-05 19:56:54 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:56:54] "GET /random?protocol=https HTTP/1.1" 500 -
2019-56-05 19:56:55 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-56-05 19:56:55 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:56:55] "GET /random?protocol=https HTTP/1.1" 500 -
2019-57-05 19:57:08 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-57-05 19:57:08 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:57:08] "GET /random?protocol= HTTP/1.1" 500 -
2019-57-05 19:57:12 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-57-05 19:57:12 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:57:12] "GET /random?protocol=1 HTTP/1.1" 500 -
2019-57-05 19:57:22 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-57-05 19:57:51 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:57:51] "GET / HTTP/1.1" 404 -
2019-59-05 19:59:10 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-59-05 19:59:10 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:59:10] "GET /random?domain HTTP/1.1" 500 -
2019-59-05 19:59:14 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-59-05 19:59:14 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:59:14] "GET /random?domain=jd HTTP/1.1" 500 -
2019-59-05 19:59:20 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-59-05 19:59:20 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 19:59:20] "GET /random?domain=jd.com HTTP/1.1" 500 -
2019-01-05 20:01:30 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-02-05 20:02:11 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-02-05 20:02:11 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:02:11] "GET /random?protocol=http HTTP/1.1" 500 -
2019-02-05 20:02:15 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-02-05 20:02:15 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:02:15] "GET /random?protocol=http HTTP/1.1" 500 -
2019-02-05 20:02:16 app.py[line:1891] ERROR Exception on /random [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 17, in random
    proxy=self.mongo_pool.random_proxy(protocol,domain,count=PROXIES_MAX_COUNT,nick_type=2)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 104, in random_proxy
    return random.choice(proxy_list)
  File "F:\anaconda\lib\random.py", line 258, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
2019-02-05 20:02:16 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:02:16] "GET /random?protocol=http HTTP/1.1" 500 -
2019-02-05 20:02:29 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-02-05 20:02:40 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16888/ (Press CTRL+C to quit)
2019-03-05 20:03:23 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-05-05 20:05:16 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:05:16] "GET /random HTTP/1.1" 200 -
2019-05-05 20:05:16 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:05:16] "GET /favicon.ico HTTP/1.1" 404 -
2019-05-05 20:05:24 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:05:24] "GET /random HTTP/1.1" 200 -
2019-05-05 20:05:26 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:05:26] "GET /random HTTP/1.1" 200 -
2019-05-05 20:05:39 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:05:39] "GET /random?protocol=http HTTP/1.1" 200 -
2019-05-05 20:05:40 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:05:40] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:00 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:00] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:11 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:11] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:12 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:12] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:17 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:17] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:22 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:22] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:26 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-06-05 20:06:29 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:29] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:30 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:30] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:30 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:30] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:31 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:31] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:31 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:31] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:31 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:31] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:32 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:32] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:32 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:32] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:32 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:32] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:32 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:32] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:32 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:32] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:33 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:33] "GET /random?protocol=http HTTP/1.1" 200 -
2019-06-05 20:06:33 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:06:33] "GET /random?protocol=http HTTP/1.1" 200 -
2019-12-05 20:12:20 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-12-05 20:12:28 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-12-05 20:12:50 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:12:50] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-13-05 20:13:17 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:13:17] "GET /proxies HTTP/1.1" 200 -
2019-15-05 20:15:52 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:15:52] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-16-05 20:16:19 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-16-05 20:16:22 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:16:22] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-16-05 20:16:52 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:16:52] "GET /proxies?protocol=https HTTP/1.1" 200 -
2019-18-05 20:18:32 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-18-05 20:18:47 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 32, in proxies
    proxies = self.proxy_pool.get_proxies(protocol=protocol, domain=domain, count=settings.AVAILABLE_IP_COUNT)
AttributeError: 'Proxy_Api' object has no attribute 'proxy_pool'
2019-18-05 20:18:47 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:18:47] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-19-05 20:19:06 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-19-05 20:19:11 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 32, in proxies
    proxies = self.mongo_pool.get_proxies(protocol=protocol, domain=domain, count=settings.AVAILABLE_IP_COUNT)
AttributeError: 'Proxy_Api' object has no attribute 'proxy_pool'
2019-19-05 20:19:11 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:19:11] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-19-05 20:19:35 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-19-05 20:19:38 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 32, in proxies
    #字典转换成json
AttributeError: 'Proxy_Api' object has no attribute 'proxy_pool'
2019-19-05 20:19:38 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:19:38] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-19-05 20:19:45 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 32, in proxies
    #字典转换成json
AttributeError: 'Proxy_Api' object has no attribute 'proxy_pool'
2019-19-05 20:19:45 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:19:45] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-19-05 20:19:46 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 32, in proxies
    #字典转换成json
AttributeError: 'Proxy_Api' object has no attribute 'proxy_pool'
2019-19-05 20:19:46 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:19:46] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-19-05 20:19:54 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-19-05 20:19:57 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:19:57] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-22-05 20:22:41 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:22:41] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-24-05 20:24:29 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:24:29] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-24-05 20:24:30 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:24:30] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-24-05 20:24:33 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:24:33] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-24-05 20:24:34 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:24:34] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-25-05 20:25:00 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-25-05 20:25:04 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:25:04] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-26-05 20:26:51 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-26-05 20:26:54 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:26:54] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-27-05 20:27:09 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-27-05 20:27:12 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 35, in proxies
    return jsonify(proxies,ensure_ascii=False)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\json\__init__.py", line 363, in jsonify
    raise TypeError("jsonify() behavior undefined when passed both args and kwargs")
TypeError: jsonify() behavior undefined when passed both args and kwargs
2019-27-05 20:27:12 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:27:12] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-27-05 20:27:13 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 35, in proxies
    return jsonify(proxies,ensure_ascii=False)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\json\__init__.py", line 363, in jsonify
    raise TypeError("jsonify() behavior undefined when passed both args and kwargs")
TypeError: jsonify() behavior undefined when passed both args and kwargs
2019-27-05 20:27:13 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:27:13] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-27-05 20:27:38 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-27-05 20:27:41 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:27:41] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-27-05 20:27:45 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:27:45] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-27-05 20:27:53 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-27-05 20:27:58 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:27:58] "GET /proxies?protocol=http HTTP/1.1" 200 -
2019-32-05 20:32:42 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-32-05 20:32:52 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:32:52] "GET /random?protocol=http HTTP/1.1" 200 -
2019-33-05 20:33:17 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:33:17] "GET /disable_domain?ip=120.79.147.254:9000 HTTP/1.1" 200 -
2019-33-05 20:33:33 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:33:33] "GET /disable_domain?ip=120.79.147.254:9000?domain=jd.com HTTP/1.1" 200 -
2019-34-05 20:34:14 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-34-05 20:34:17 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:34:17] "GET /disable_domain?ip=120.79.147.254:9000?domain=jd.com HTTP/1.1" 200 -
2019-34-05 20:34:20 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:34:20] "GET /disable_domain?ip=120.79.147.254:9000?domain=jd.com HTTP/1.1" 200 -
2019-37-05 20:37:28 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:37:28] "GET /disable_domain?ip=120.79.147.254:9000?domain=jd.com HTTP/1.1" 200 -
2019-37-05 20:37:41 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-37-05 20:37:52 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:37:52] "GET /disable_domain?domain=jd.com HTTP/1.1" 200 -
2019-38-05 20:38:13 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:38:13] "GET /disable_domain?ip=120.79.147.254:9000?domain=jd.com HTTP/1.1" 200 -
2019-38-05 20:38:18 app.py[line:1891] ERROR Exception on /disable_domain [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 47, in disable_domain
    return '{}禁用域名{}成功'.format(ip=ip,domain=domain)
IndexError: tuple index out of range
2019-38-05 20:38:18 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:38:18] "GET /disable_domain?ip=120.79.147.254:9000&domain=jd.com HTTP/1.1" 500 -
2019-38-05 20:38:47 app.py[line:1891] ERROR Exception on /disable_domain [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 47, in disable_domain
    return '{}禁用域名{}成功'.format(ip=ip,domain=domain)
IndexError: tuple index out of range
2019-38-05 20:38:47 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:38:47] "GET /disable_domain?ip=120.79.147.254&domain=jd.com HTTP/1.1" 500 -
2019-39-05 20:39:19 _internal.py[line:122] INFO  * Running on http://0.0.0.0:16889/ (Press CTRL+C to quit)
2019-39-05 20:39:21 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:39:21] "GET /disable_domain?ip=120.79.147.254&domain=jd.com HTTP/1.1" 200 -
2019-41-05 20:41:23 _internal.py[line:122] INFO  * Running on http://127.0.0.1:16889/ (Press CTRL+C to quit)
2019-41-05 20:41:27 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:41:27] "GET / HTTP/1.1" 404 -
2019-41-05 20:41:27 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:41:27] "GET /favicon.ico HTTP/1.1" 404 -
2019-41-05 20:41:37 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 30, in proxies
    proxies=self.mongo_pool.get_proxies(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 92, in get_proxies
    return  self.find(conditions=conditions,count=count)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 66, in find
    proxy=Proxy(**item)
TypeError: __init__() got an unexpected keyword argument 'disable_domains'
2019-41-05 20:41:37 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:41:37] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-42-05 20:42:58 _internal.py[line:122] INFO  * Running on http://127.0.0.1:16889/ (Press CTRL+C to quit)
2019-43-05 20:43:07 app.py[line:1891] ERROR Exception on /proxies [GET]
Traceback (most recent call last):
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "H:\py_project\算法与数据结构\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "H:/py_project/算法与数据结构/ip代理池/core/proxy_api.py", line 30, in proxies
    proxies=self.mongo_pool.get_proxies(protocol,domain,count=PROXIES_MAX_COUNT)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 92, in get_proxies
    return  self.find(conditions=conditions,count=count)
  File "H:\py_project\算法与数据结构\ip代理池\core\db\mongo_pool.py", line 66, in find
    proxy=Proxy(**item)
TypeError: __init__() got an unexpected keyword argument 'disable_domains'
2019-43-05 20:43:07 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:43:07] "GET /proxies?protocol=http HTTP/1.1" 500 -
2019-44-05 20:44:25 _internal.py[line:122] INFO  * Running on http://127.0.0.1:16889/ (Press CTRL+C to quit)
2019-44-05 20:44:28 _internal.py[line:122] INFO 127.0.0.1 - - [05/Aug/2019 20:44:28] "GET /proxies?protocol=http HTTP/1.1" 200 -
